doctrine:
    dbal:
        # Set the default connection to default
        default_connection: default
        connections:
            default:
                host: '%db_wallet_server%'
                dbname: '%db_wallet_dbname%'
                user: '%db_wallet_username%'
                password: '%db_wallet_password%'
                driver: pdo_mysql
                server_version: '5.6'
                port: 3306
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                options:
                    # Connect timeout 60 sec
                    2: 60

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'WalletApp\Entity'
                alias: App
