version: '3.0'

services:
  app:
    build: ./docker
    working_dir: /app
    env_file:
      - .env.local
    environment:
      - VIRTUAL_HOST=wallet.loc
    volumes:
      - .:/app
      - .env.local:/app/.env
      - ./docker/php.ini:/usr/local/etc/php/conf.d/zz.ini
      - ./docker/nginx-site.conf:/etc/nginx/conf.d/default-site.conf
    networks:
      - nginx_proxy_network
    restart: always

  wallet_db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wallet
    volumes:
      - wallet_mysql_data:/var/lib/mysql
    networks:
      - nginx_proxy_network
    restart: always

networks:
  nginx_proxy_network:
    external: true

volumes:
  wallet_mysql_data:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
